version: "3.9"
services:
  backend:
    build: .
    container_name: cs2702-backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./data:/app/data:ro
      - ./out:/app/out
    restart: unless-stopped